[package]
name = "redis-async"
version = "0.6.0"
authors = ["Ben Ashford <benashford@users.noreply.github.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "An asynchronous futures based Redis client for Rust using Tokio"
repository = "https://github.com/benashford/redis-async-rs"
keywords = ["redis", "tokio"]
edition = "2018"

[dependencies]
cfg-if = "=0.1.9" # Not used directly, but required because mio required by pre-release Tokio requires this version

bytes = { git = "https://github.com/tokio-rs/bytes.git", branch = "master" }
log = "0.4"
futures-channel = "0.3"
futures-sink = "0.3"
futures-util = "0.3"
tokio = { git = "https://github.com/tokio-rs/tokio.git", branch = "master", features = ["rt-core", "net", "time"] }
tokio-util = { git = "https://github.com/tokio-rs/tokio.git", branch = "master", features = ["codec"] }

[dev-dependencies]
env_logger = "0.7"
futures = "0.3"
tokio = { git = "https://github.com/tokio-rs/tokio.git", branch = "master", features = ["rt-threaded", "macros"] }
