[package]
name = "redis-async"
version = "0.6.0"
authors = ["Ben Ashford <benashford@users.noreply.github.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "An asynchronous futures based Redis client for Rust using Tokio"
repository = "https://github.com/benashford/redis-async-rs"
keywords = ["redis", "tokio"]
edition = "2018"

[dependencies]
bytes = "0.4"
log = "0.4"
futures-util-preview = "=0.3.0-alpha.18"
tokio-codec = "0.2.0-alpha.2"
tokio-executor = "0.2.0-alpha.2"
tokio-net = "0.2.0-alpha.2"
tokio-timer = "0.3.0-alpha.2"

[dev-dependencies]
env_logger = "0.6"
futures-preview = "=0.3.0-alpha.18"
tokio = "0.2.0-alpha.2"
